# Generated by Django 4.2.13 on 2024-05-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registereduser', '0002_alter_registereduser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='token',
        ),
    ]
