# Generated by Django 4.2.13 on 2024-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registereduser', '0003_remove_registereduser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
