# Generated by Django 4.2.13 on 2024-05-23 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registereduser', '0004_alter_registereduser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
