# Generated by Django 4.2.13 on 2024-05-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('registereduser', '0005_registereduser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateTimeField()),
                ('body_text', models.TextField()),
                ('url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to='registereduser.registereduser')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='source.source')),
            ],
            options={
                'unique_together': {('url', 'created_by')},
            },
        ),
    ]
