# Generated by Django 4.2.13 on 2024-05-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registereduser', '0005_registereduser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=5000)),
                ('source_url', models.URLField(max_length=2000)),
                ('story_count', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(max_length=50)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registereduser.registereduser', verbose_name='user')),
            ],
            options={
                'unique_together': {('source_user', 'source_url')},
            },
        ),
    ]
